version: '3'
services:
  activemq:
    container_name: 'activemq'
    image: freekode/activemq
    ports:
      - '61616:61616'
      - '8161:8161'
  platform-binance:
    container_name: 'platform-binance'
    build: .
    depends_on:
      - activemq
    ports:
      - '8081:8080'
    environment:
      - EVENT_BROKER_URL=tcp://activemq:61616
      - BINANCE_API_KEY=test-key
      - BINANCE_API_SECRET=test-secret

